<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>kintobo sector managment</title>

<?php
  	session_start();
	unset($_SESSION['manId']);
	unset($_SESSION['SESS_PASSWORD']);
	unset($_SESSION['SESS_USERNAME']);
?>

</head>

<body bgcolor="#993300">
 
 
 
 
 
 
 <div style="background-color:#999900; width:800px; height:500px; border-style:ridge; border-bottom-style:inset; border-collapse:collapse; margin:0px auto 0px auto">
 
<div style="background-color:#66FF99; width:800px; height:140px"><img src="photo/head.png" /></div>
<div style="background-color:#999900; width:800px; height:40px"> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>


<style type="text/css" media="screen">
body{ behavior:url("csshover2.htc"); }
.pd_menu_01 {float:left; padding:0; margin:0;color: #FFFFFF;background: #0000A0;width:100%; border:solid 1px #004080;clear:both;} /*Color navigation bar normal mode*/
.pd_menu_01  a, .pd_menu_01 a:visited {
font-family:Arial, Helvetica, sans-serif;
font-style:normal;
font-weight:bold;
font-size:12px;
color: #FFFFFF;
background-color: #0000A0;
text-decoration: none;
}
.pd_menu_01 ul {list-style-type:none;padding:0; margin:0;}
.pd_menu_01 ul li {float:left; position:relative; z-index:auto !important ; z-index:1000 ; border-right:solid 1px #004080; border-left:solid 1px #004080;}
.pd_menu_01 ul li a {color: #FFFFFF;background: #0000A0;float:none !important ; float:left ; display:block; height:30px; line-height:30px; padding:0 10px 0 10px; text-decoration:none; }
.pd_menu_01 ul li ul {display:none; border:none;color: #FFFFFF;background: #0000A0; width:1px}
.pd_menu_01 ul li:hover a {background-color:#008000; text-decoration:none; color:#FFFF00;} /*Color main cells hovering mode*/
.pd_menu_01 ul li:hover ul {display:block;  position:absolute; z-index:999; top:29px; margin-top:1px; left:0;}
.pd_menu_01 ul li:hover ul li a {display:block; width:12em; height:auto; line-height:1.3em; margin-left:-1px; padding:5px 10px 5px 10px; border-left:solid 1px #004080; border-bottom: solid 1px #004080; background-color:#0000FF;  color:#FFFFFF;} /*Color subcells normal mode*/
.pd_menu_01 ul li:hover ul li a:hover {background-color:#CA0000; text-decoration:none;color:#FFFF00;} /*Color subcells hovering mode*/
.pd_menu_01 ul li a:hover {background-color:#008000; text-decoration:none;color:#FFFF00;} /*Color main cells hovering mode*/
.pd_menu_01 ul li a:hover ul {display:block; width:12em; position:absolute; z-index:999; top:29px; left:0; }
.pd_menu_01 ul li ul li a:visited { background-color:#0000FF;  color:#FFFFFF;} /*Color subcells normal mode*/
.pd_menu_01 ul li a:hover ul li a {display:block; width:12em; height:1px; line-height:1.3em; padding:4px 16px 4px 16px; border-left:solid 1px #004080; border-bottom: solid 1px #004080; background-color:#0000FF;  color:#FFFFFF;} 
.pd_menu_01 ul li a:hover ul li a:hover {background-color:#CA0000; text-decoration:none;color:#FFFF00;} /*Color subcells hovering mode*/
</style>
</head>
<body>

<div class="pd_menu_01 "> 
<ul><li><a href="#">HOME</a>
</li></ul>

<ul><li><a href="#">CONTACT US</a>
</li></ul>

<ul><li><a href="#">HELP</a>

</ul>
</li>

<ul><li><a href="#">ABOUT US</a>

</div>

</body>
</html>
</div>




<div style="width:800px; height:300px; background-color:#999900; background-image:url(photo/index.png); margin:0px auto 0px auto"><form action="execute.php" method="post">
<table align="center" cellpadding="5" cellspacing="5">
  <tr>
    <td align="right"><font face="Verdana, Arial, Helvetica, sans-serif"; size="+2"; color="#333300">USERNAME</font></td>
    <td><input name="username" type="text" /></td>
  </tr>
   <tr>
    <td align="right"><font face="Verdana, Arial, Helvetica, sans-serif"; size="+2"; color="#333300">PASSWORD</font></td>
    <td><input name="password" type="password" /></td>
  </tr>
  <tr>
    <td></td>
    <td><input type="submit" name="login" value="LOGIN" /></td>
  </tr>
</table>
</form></div>
<div style="width:800px; height:20px; background-color:#333300;"><center><b><font color="#CCFFFF">Designed and Developed   by	UWAMAHORO Josiane in 2016 in S6(C.S.M)</font>
</b></center></div>
</body>
</html>


